### PR TITLE
:bug: N°5403 - Notifications not working if "email-reply" not enabled by default

### PR DESCRIPTION
**Pull request by larhip**
Fix a regression when 'enabled_default' is set to false

### CODE REVIEW

**Comment by piRGoif** [comment]
Hello Lars, can you explain a bit more the problem, ways to reproduce ?

**Comment by larhip** [comment]
Hi @piRGoif 

It should be documented in the linked bug ticket (5403) or at least in in the ticket (R-033622) which is linked to the bug?

Anyhow I could try to explain the bug at this place as well 🙂 

If you change your iTop settings to the following:

```
'email-reply' => array(
  'enabled_default' => false
)
```

And then try to send a notification in a public log by manual enable the checkbox, nothing will happen, no notification will be send. 
Which means: As soon as you set the option above with iTop 3 the TriggerOnLogUpdate never get activated (even with an manual enabled checkbox). With iTop 3 email-reply is not usable in combination with this config param.
 
Does this help to reproduce the bug?

Cheers
Lars

**Comment by Molkobain** [comment]
Will be discussed during functional review about the behavior change. As it should restore the behavior documented in the wiki, it should be ok.

**Comment by piRGoif** [comment]
Functional review : accepted

**Pull request merged**
